# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-09-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230911_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_problems', to='web.UserInfo', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='mode',
            field=models.SmallIntegerField(choices=[(1, '公开模式'), (2, '隐私模式')], default=1, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('success', '低'), ('warning', '中'), ('danger', '高')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(7, '重新打开'), (3, '已解决'), (6, '已关闭'), (2, '处理中'), (1, '新建'), (4, '已忽略'), (5, '待反馈')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (1, '免费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(7, '#20bfa3'), (6, '#7461c2'), (3, '#ebc656'), (5, '#20bFA4'), (1, '#56b8eb'), (4, '#a2d148'), (2, '#f28033')], default=1, verbose_name='颜色'),
        ),
    ]
