# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-09-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230912_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('success', '低'), ('danger', '高'), ('warning', '中')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '已忽略'), (2, '处理中'), (3, '已解决'), (6, '已关闭'), (7, '重新打开'), (1, '新建'), (5, '待反馈')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (1, '免费版'), (2, '收费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(2, '#f28033'), (5, '#20bFA4'), (6, '#7461c2'), (4, '#a2d148'), (3, '#ebc656'), (1, '#56b8eb'), (7, '#20bfa3')], default=1, verbose_name='颜色'),
        ),
    ]
