# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-09-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20230912_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('danger', '高'), ('warning', '中'), ('success', '低')], default='danger', max_length=12, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(6, '已关闭'), (2, '处理中'), (7, '重新打开'), (5, '待反馈'), (4, '已忽略'), (3, '已解决'), (1, '新建')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#20bFA4'), (2, '#f28033'), (3, '#ebc656'), (7, '#20bfa3'), (6, '#7461c2'), (1, '#56b8eb'), (4, '#a2d148')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], verbose_name='状态'),
        ),
    ]
