# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-09-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20230914_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='mode',
            field=models.SmallIntegerField(choices=[(1, '公开模式'), (2, '隐私模式')], default=1, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '处理中'), (6, '已关闭'), (4, '已忽略'), (1, '新建'), (7, '重新打开'), (3, '已解决'), (5, '待反馈')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (1, '免费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(2, '#f28033'), (3, '#ebc656'), (5, '#20bFA4'), (4, '#a2d148'), (6, '#7461c2'), (7, '#20bfa3'), (1, '#56b8eb')], default=1, verbose_name='颜色'),
        ),
    ]
